const os = require('node:os')

console.log('Información del sistema operativo')
console.log('----------------------------------')
console.log('Nombre del sistema: ', os.platform())
console.log('Versión: ', os.release())
console.log('Architecture: ', os.arch())
console.log('CPUs: ', os.cpus())
console.log('Memoria libre: ', os.freemem() / 1024 / 1024)
console.log('Memoria total: ', os.totalmem() / 1024 / 1024)
