### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/f9c33f0c-aa52-11ee-b5c4-e55d218e6757

### Recuperar todas las películas por género
GET http://localhost:1234/movies?genre=action

### Crear una película
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": ["Crime", "Drama"]
}

### Actualizar una película
PATCH http://localhost:1234/movies/9115ce28-aa63-11ee-b5c4-e55d218e6757
Content-Type: application/json

{
  "year" : 1993
}

### Borrar una pelicula
DELETE http://localhost:1234/movies/1dae78f8-aa64-11ee-b5c4-e55d218e6757